on:
  push:
    branches:
      - v2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "hb0730/pure-admin-thin"
          source_branch: "v2"
          destination_repo: "hb0730/boot-admin-ui"
          destination_branch: "v4"
